version: "3.8"

services:
  php:
    build: ./php
    container_name: php-apache
    volumes:
      - ./php:/var/www/html
    ports:
      - "8000:80"

  db:
    image: mysql:8.0
    container_name: mysql-db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpass
      MYSQL_DATABASE: miapp
      MYSQL_USER: userapp
      MYSQL_PASSWORD: userpass
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    restart: always
    ports:
      - "8001:80"
    environment:
      PMA_HOST: db
      PMA_USER: userapp
      PMA_PASSWORD: userpass

volumes:
  db_data:

